### ISSUE TITLE
highlight will mess up after some editing?

### ISSUE THREAD

**Issue by taooceros** [sharpSteff/lapce-csharp-plugin#3]
![image](https://user-images.githubusercontent.com/45326534/228300811-839cf01a-ebce-44ac-be09-eae2fb58d5cc.png)

**Comment by taooceros** [comment]
Also seems like I wasn't able to load any assembly🤔
![image](https://user-images.githubusercontent.com/45326534/228304178-e3230f86-627c-4229-a26f-f73a63692808.png)

**Comment by sharpSteff** [comment]
are you on 0.27 ?

**Comment by taooceros** [comment]
I think I am on nightly because there's no windows build for 0.27

**Comment by sharpSteff** [comment]
i'll check if I can reproduce the issue

**Comment by taooceros** [comment]
Thanks

**Comment by sharpSteff** [comment]
rootcause is probably OmniSharp/omnisharp-roslyn#2483

**Comment by taooceros** [comment]
oh 🤣thanks for investigating this! so microsoft's lsp doesn't follow lsp spec. interesting...

**Comment by sharpSteff** [comment]
@taooceros 
please check v.2.0.0 I dropped omnisharp and switched to the open source project [csharp-ls](https://github.com/razzmatazz/csharp-language-server) as LSP, which works out of the box after installing the LSP via:
`dotnet tool install --global csharp-ls`

**Comment by taooceros** [comment]
Thanks for helping! I will try it now

**Comment by taooceros** [comment]
~~emmmm I can't get it to work. The csharp-ls is installed, but it seems like the lsp is not running? do I need to uninstall and reinstall?~~

oh ok I need to delete some setting..
